### ISSUE TITLE
QMEUを走らせると...

### ISSUE THREAD

**Issue by Wiki0617** [hxbdy/emu84#1]
QEMUを起動すると
なぜかemu84\z_tools\qemu\fdimage0.binが変更されるらしく、VScode上の変更判定が入る。
<img width="960" alt="QEMU起動時のbin変更" src="https://user-images.githubusercontent.com/66894432/84586316-6a782a00-ae53-11ea-91a4-fbd7ae5517d4.PNG">

**Comment by hxbdy** [comment]
z_tools以下は変更することはないので、.gitignoreに追記したほうがいいかも

**Comment by hxbdy** [comment]
一度プッシュ済みのファイルだったため、.gitignoreに追記するだけでは除外されない。
現在その現象を再現できないため、gitキャッシュを一度クリアして本issueをクローズする。
再現した時は、再度キャッシュクリア後、.gitignoreに当該ファイルを追記すること。
$ git rm --cached [削除したいファイル]　/* ファイルを残したまま管理対象から外す。ファイルを残した場合は必ず.gitignoreに追記すること */
